# Generated by Django 3.0.6 on 2020-05-28 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('T', 'teacher'), ('S', 'student')], max_length=1)),
                ('object_type', models.CharField(choices=[('T', 'teacher'), ('S', 'student')], max_length=1)),
                ('message_way', models.CharField(choices=[('S', 'send'), ('R', 'receive')], max_length=1)),
                ('message_type', models.CharField(choices=[('T', 'txt'), ('P', 'picture')], default='T', max_length=1)),
                ('message_content', models.BinaryField()),
                ('message_time', models.DateTimeField(auto_now_add=True)),
                ('object_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='n_messages', to='user.Student')),
                ('object_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='n_messages', to='user.Teacher')),
                ('owner_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_messages', to='user.Student')),
                ('owner_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_messages', to='user.Teacher')),
            ],
        ),
    ]
