# Generated by Django 3.0.6 on 2020-06-19 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('T', 'teacher'), ('S', 'student')], max_length=1)),
                ('receiver_type', models.CharField(choices=[('T', 'teacher'), ('S', 'student')], max_length=1)),
                ('message_type', models.CharField(choices=[('T', 'txt'), ('P', 'picture')], default='T', max_length=1)),
                ('message_content', models.BinaryField()),
                ('message_time', models.DateTimeField(auto_now_add=True)),
                ('receiver_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_messages', to='user.Student')),
                ('receiver_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_messages', to='user.Teacher')),
                ('sender_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s_messages', to='user.Student')),
                ('sender_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s_messages', to='user.Teacher')),
            ],
        ),
    ]
