# Generated by Django 3.0.6 on 2020-05-30 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_messages', to='user.Student'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_messages', to='user.Teacher'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s_messages', to='user.Student'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s_messages', to='user.Teacher'),
        ),
    ]
