# Generated by Django 3.0.6 on 2020-05-25 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=16)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('U', 'unknown')], default='U', max_length=1)),
                ('picture', models.ImageField(upload_to='')),
                ('signature', models.CharField(max_length=1024)),
                ('school', models.CharField(max_length=32)),
                ('department', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=32)),
                ('introduction', models.CharField(max_length=51200)),
                ('research_fields', models.CharField(max_length=51200)),
                ('research_achievements', models.CharField(max_length=51200)),
                ('phone', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('homepage', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('teacher_number', models.CharField(max_length=32)),
                ('id_number', models.CharField(max_length=32)),
                ('auth_state', models.CharField(choices=[('UQ', 'unqualified'), ('QD', 'qualified')], default='UQ', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=16)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('U', 'unknown')], default='U', max_length=1)),
                ('picture', models.ImageField(upload_to='')),
                ('signature', models.CharField(max_length=1024)),
                ('school', models.CharField(max_length=32)),
                ('department', models.CharField(max_length=32)),
                ('major', models.CharField(max_length=32)),
                ('introduction', models.CharField(max_length=51200)),
                ('research_experience', models.CharField(max_length=51200)),
                ('phone', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('homepage', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('student_number', models.CharField(max_length=32)),
                ('id_number', models.CharField(max_length=32)),
                ('auth_state', models.CharField(choices=[('UQ', 'unqualified'), ('QD', 'qualified')], default='UQ', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
