# Generated by Django 3.0.6 on 2020-06-03 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=16)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('U', 'unknown')], default='U', max_length=1)),
                ('school', models.CharField(max_length=32)),
                ('department', models.CharField(max_length=32)),
                ('title', models.CharField(choices=[('TA', 'assistant'), ('LT', 'lecturer'), ('AP', 'associate professor'), ('PP', 'professor')], default='TA', max_length=2)),
                ('auth_state', models.CharField(choices=[('UQ', 'unqualified'), ('QD', 'qualified')], default='UQ', max_length=2)),
                ('picture', models.ImageField(upload_to=user.models.custom_upload_path)),
                ('signature', models.CharField(max_length=1024)),
                ('phone', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('homepage', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('teacher_number', models.CharField(max_length=32)),
                ('id_number', models.CharField(max_length=32)),
                ('introduction', models.CharField(max_length=51200)),
                ('research_fields', models.CharField(max_length=51200)),
                ('research_achievements', models.CharField(max_length=51200)),
                ('promotional_video_url', models.CharField(max_length=1024)),
                ('follows', models.ManyToManyField(related_name='teacher_fans', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=16)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('U', 'unknown')], default='U', max_length=1)),
                ('school', models.CharField(max_length=32)),
                ('department', models.CharField(max_length=32)),
                ('major', models.CharField(max_length=32)),
                ('degree', models.CharField(choices=[('UG', 'undergraduate'), ('MT', 'master'), ('DT', 'doctor')], default='UG', max_length=2)),
                ('auth_state', models.CharField(choices=[('UQ', 'unqualified'), ('QD', 'qualified')], default='UQ', max_length=2)),
                ('picture', models.ImageField(upload_to=user.models.custom_upload_path)),
                ('signature', models.CharField(max_length=1024)),
                ('phone', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('homepage', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('student_number', models.CharField(max_length=32)),
                ('id_number', models.CharField(max_length=32)),
                ('introduction', models.CharField(max_length=51200)),
                ('research_interest', models.CharField(max_length=51200)),
                ('research_experience', models.CharField(max_length=51200)),
                ('promotional_video_url', models.CharField(max_length=1024)),
                ('follows', models.ManyToManyField(related_name='student_fans', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
